/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.editortexto;

import java.awt.Color;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.Buffer;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.text.Normalizer.Form;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author hierr
 */
public class editor extends javax.swing.JFrame {

    /**
     * Creates new form editor
     */
    
    static File archivoEditado= new File("");
    static String buffer = new String("");
    
    public editor() {
        initComponents();
        setLocationRelativeTo(null);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("TEXT FILES","txt","text");
        FileChooser.setFileFilter(filter);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ModalAcercaDe = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jOptionPane1 = new javax.swing.JOptionPane();
        FileChooserFrame = new javax.swing.JFrame();
        FileChooser = new javax.swing.JFileChooser();
        dialogoGuardar = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BotonGuardar2 = new javax.swing.JToggleButton();
        BotonNoGuardar = new javax.swing.JToggleButton();
        BotonCancelar = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        FileSaverFrame = new javax.swing.JFrame();
        FileSaver = new javax.swing.JFileChooser();
        DialogFormato = new javax.swing.JDialog();
        String[] fonts = GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames();
        ComboBoxFuente = new javax.swing.JComboBox<>(fonts);
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        SpinnerTamaño = new javax.swing.JSpinner();
        ComboBoxMasEstilos = new javax.swing.JComboBox<>();
        BotonColor = new javax.swing.JButton();
        FrameColorChooser = new javax.swing.JFrame();
        ColorChooser = new javax.swing.JColorChooser();
        jPanel8 = new javax.swing.JPanel();
        BotonSeleccionarColor = new javax.swing.JButton();
        BotonCancelarColor = new javax.swing.JButton();
        DialogoDatos = new javax.swing.JFrame();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        FunPalabras = new javax.swing.JLabel();
        FunCaracteres = new javax.swing.JLabel();
        FunTamaño = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        FunUbicacion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaTexto = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        EtiquetaNombreArchivo = new javax.swing.JLabel();
        PanelDatos = new javax.swing.JPanel();
        EtiquetaDatos = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuArchivo = new javax.swing.JMenu();
        BotonNuevo = new javax.swing.JMenuItem();
        BotonAbrirArchivo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        BotonGuardarArchivo = new javax.swing.JMenuItem();
        BotonGuardarComo = new javax.swing.JMenuItem();
        MenuFormato = new javax.swing.JMenu();
        BotonCambiarFormato = new javax.swing.JMenuItem();
        MenuAcercaDe = new javax.swing.JMenu();
        BotonDatosDel = new javax.swing.JMenuItem();

        ModalAcercaDe.setLocationRelativeTo(null);
        ModalAcercaDe.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        ModalAcercaDe.setTitle("Datos del desarrollador");
        ModalAcercaDe.setAlwaysOnTop(true);
        ModalAcercaDe.setModal(true);
        ModalAcercaDe.setName("Acerca del creador"); // NOI18N
        ModalAcercaDe.setSize(new java.awt.Dimension(200, 200));
        ModalAcercaDe.getContentPane().setLayout(new javax.swing.BoxLayout(ModalAcercaDe.getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jOptionPane1.setMessage("Hecho por Pablo Hierrezuelo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jOptionPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jOptionPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        ModalAcercaDe.getContentPane().add(jPanel3);

        FileChooserFrame.setSize(new java.awt.Dimension(850, 400));
        FileChooserFrame.getContentPane().setLayout(new javax.swing.BoxLayout(FileChooserFrame.getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        FileChooser.setApproveButtonText("OK");
        FileChooser.setFileHidingEnabled(true);
        FileChooser.setToolTipText("");
        FileChooser.setDragEnabled(true);
        FileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileChooserActionPerformed(evt);
            }
        });
        FileChooserFrame.getContentPane().add(FileChooser);

        dialogoGuardar.setLocationRelativeTo(null);
        dialogoGuardar.setSize(new java.awt.Dimension(400, 250));
        dialogoGuardar.getContentPane().setLayout(new javax.swing.BoxLayout(dialogoGuardar.getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("¿Quieres guardar los cambios?");

        BotonGuardar2.setText("GUARDAR");
        BotonGuardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardar2ActionPerformed(evt);
            }
        });

        BotonNoGuardar.setText("NO GUARDAR");
        BotonNoGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNoGuardarActionPerformed(evt);
            }
        });

        BotonCancelar.setText("CANCELAR");
        BotonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelarActionPerformed(evt);
            }
        });

        jLabel3.setText("ATENCIÓN: ESTÁS APUNTO DE PERDER TODOS LOS CAMBIOS");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(BotonGuardar2)
                .addGap(18, 18, 18)
                .addComponent(BotonNoGuardar)
                .addGap(18, 18, 18)
                .addComponent(BotonCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addGap(50, 50, 50)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonGuardar2)
                    .addComponent(BotonNoGuardar)
                    .addComponent(BotonCancelar))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        dialogoGuardar.getContentPane().add(jPanel4);

        FileSaver.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        FileSaver.setApproveButtonText("GUARDAR");
        FileSaver.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        FileSaver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileSaverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FileSaverFrameLayout = new javax.swing.GroupLayout(FileSaverFrame.getContentPane());
        FileSaverFrame.getContentPane().setLayout(FileSaverFrameLayout);
        FileSaverFrameLayout.setHorizontalGroup(
            FileSaverFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(FileSaverFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FileSaverFrameLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(FileSaver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        FileSaverFrameLayout.setVerticalGroup(
            FileSaverFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(FileSaverFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FileSaverFrameLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(FileSaver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        DialogFormato.setLocationRelativeTo(null);
        DialogFormato.setTitle("Editar formato de texto");
        DialogFormato.setSize(new java.awt.Dimension(550, 300));

        ComboBoxFuente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxFuenteItemStateChanged(evt);
            }
        });
        ComboBoxFuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxFuenteActionPerformed(evt);
            }
        });

        jLabel4.setText("Fuente");

        jLabel6.setText("Tamaño");

        jLabel8.setText("Más Estilos");

        jLabel5.setText("Color");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(165, 165, 165)
                .addComponent(jLabel6)
                .addGap(46, 46, 46)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(73, 73, 73))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SpinnerTamaño.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SpinnerTamaño.setValue(12);
        SpinnerTamaño.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpinnerTamañoStateChanged(evt);
            }
        });

        ComboBoxMasEstilos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Capitalizar", "Mayúsculas", "Minúsculas", "CamelCase", "C.especiales" }));
        ComboBoxMasEstilos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxMasEstilosActionPerformed(evt);
            }
        });

        BotonColor.setText("Elegir");
        BotonColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonColorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DialogFormatoLayout = new javax.swing.GroupLayout(DialogFormato.getContentPane());
        DialogFormato.getContentPane().setLayout(DialogFormatoLayout);
        DialogFormatoLayout.setHorizontalGroup(
            DialogFormatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(DialogFormatoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ComboBoxFuente, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(SpinnerTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(ComboBoxMasEstilos, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(BotonColor)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        DialogFormatoLayout.setVerticalGroup(
            DialogFormatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogFormatoLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DialogFormatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DialogFormatoLayout.createSequentialGroup()
                        .addGroup(DialogFormatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SpinnerTamaño)
                            .addComponent(ComboBoxMasEstilos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonColor))
                        .addGap(1, 1, 1))
                    .addComponent(ComboBoxFuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        FrameColorChooser.setAlwaysOnTop(true);
        FrameColorChooser.setSize(new java.awt.Dimension(500, 250));
        FrameColorChooser.getContentPane().add(ColorChooser, java.awt.BorderLayout.CENTER);

        BotonSeleccionarColor.setText("Seleccionar");

        BotonCancelarColor.setText("Cancelar");
        BotonCancelarColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelarColorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(BotonSeleccionarColor)
                .addGap(30, 30, 30)
                .addComponent(BotonCancelarColor)
                .addContainerGap(208, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonSeleccionarColor)
                    .addComponent(BotonCancelarColor))
                .addContainerGap())
        );

        FrameColorChooser.getContentPane().add(jPanel8, java.awt.BorderLayout.PAGE_END);

        DialogoDatos.setSize(new java.awt.Dimension(200, 290));

        jLabel10.setText("Palabras");

        jLabel11.setText("Caracteres");

        jLabel12.setText("Tamaño (bytes)");

        javax.swing.GroupLayout DialogoDatosLayout = new javax.swing.GroupLayout(DialogoDatos.getContentPane());
        DialogoDatos.getContentPane().setLayout(DialogoDatosLayout);
        DialogoDatosLayout.setHorizontalGroup(
            DialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogoDatosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(DialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(DialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FunPalabras)
                    .addComponent(FunCaracteres)
                    .addComponent(FunTamaño))
                .addGap(36, 36, 36))
        );
        DialogoDatosLayout.setVerticalGroup(
            DialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogoDatosLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(DialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(FunPalabras))
                .addGap(46, 46, 46)
                .addGroup(DialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(FunCaracteres))
                .addGap(45, 45, 45)
                .addGroup(DialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(FunTamaño))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NotePadblo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(FunUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(FunUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        AreaTexto.setColumns(20);
        AreaTexto.setRows(5);
        AreaTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AreaTextoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(AreaTexto);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EtiquetaNombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EtiquetaNombreArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, 12, Short.MAX_VALUE)
        );

        PanelDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelDatosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelDatosMouseExited(evt);
            }
        });
        PanelDatos.setLayout(new java.awt.BorderLayout());

        EtiquetaDatos.setText("    Datos");
        EtiquetaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EtiquetaDatosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EtiquetaDatosMouseExited(evt);
            }
        });
        PanelDatos.add(EtiquetaDatos, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        MenuArchivo.setText("Archivo");
        MenuArchivo.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                MenuArchivoMenuSelected(evt);
            }
        });
        MenuArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuArchivoActionPerformed(evt);
            }
        });

        BotonNuevo.setText("Nuevo");
        BotonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNuevoActionPerformed(evt);
            }
        });
        MenuArchivo.add(BotonNuevo);

        BotonAbrirArchivo.setText("Abrir Archivo");
        BotonAbrirArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAbrirArchivoMouseClicked(evt);
            }
        });
        BotonAbrirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAbrirArchivoActionPerformed(evt);
            }
        });
        MenuArchivo.add(BotonAbrirArchivo);
        MenuArchivo.add(jSeparator1);

        BotonGuardarArchivo.setText("Guardar");
        BotonGuardarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarArchivoActionPerformed(evt);
            }
        });
        MenuArchivo.add(BotonGuardarArchivo);

        BotonGuardarComo.setText("Guardar Como");
        BotonGuardarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarComoActionPerformed(evt);
            }
        });
        MenuArchivo.add(BotonGuardarComo);

        jMenuBar1.add(MenuArchivo);

        MenuFormato.setText("Formato");
        MenuFormato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFormatoActionPerformed(evt);
            }
        });

        BotonCambiarFormato.setText("Editar Formato");
        BotonCambiarFormato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCambiarFormatoActionPerformed(evt);
            }
        });
        MenuFormato.add(BotonCambiarFormato);

        jMenuBar1.add(MenuFormato);

        MenuAcercaDe.setText("Acerca de");
        MenuAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAcercaDeActionPerformed(evt);
            }
        });

        BotonDatosDel.setText("Datos del desarrollador");
        BotonDatosDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDatosDelActionPerformed(evt);
            }
        });
        MenuAcercaDe.add(BotonDatosDel);

        jMenuBar1.add(MenuAcercaDe);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuArchivoMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_MenuArchivoMenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuArchivoMenuSelected
/**
 * Cuando se pusa el botón Guardar Como, se abre el diálogo FileSaver (que contiene un FileChooser en modo guardar)
 * El nombre del archivo pasa a rellenar la etiqueta EtiquetaNombreArchivo, que el usuario verá encima del text area
 * @param evt 
 */
    private void BotonGuardarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarComoActionPerformed
        File saver;
        PrintWriter printwriter = null;

        int status = FileSaver.showSaveDialog(jPanel1);
        if (status==0) {
            try {
                saver = FileSaver.getSelectedFile();
                printwriter = new PrintWriter(saver);
                printwriter.write(AreaTexto.getText());
                printwriter.close();
                EtiquetaNombreArchivo.setText(FileSaver.getSelectedFile().getName());
                FunUbicacion.setText(FileSaver.getSelectedFile().getPath());
           
            } catch (FileNotFoundException ex) {
                Logger.getLogger(editor.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        
    }//GEN-LAST:event_BotonGuardarComoActionPerformed

    private void MenuAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAcercaDeActionPerformed
     
      
        
    }//GEN-LAST:event_MenuAcercaDeActionPerformed
/**
 * EL botón Datos Del Programador abre el ModalAcercaDe
 * @param evt 
 */
    private void BotonDatosDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDatosDelActionPerformed
       ModalAcercaDe.setVisible(true);
    }//GEN-LAST:event_BotonDatosDelActionPerformed
/**
 * El BotonAbrirArchivo se encuentra dentro del menú Archivo
 * Si hay texto escrito que no está guardado en un archivo, se abre el dialogoGuardar, que avisa al usuario que está apunto de perder sus avances
 * Si el texto está guardado en un archivo pero ha sido modificado, también se abre el dialogoGuardar
 * En caso de que no haya nada escrito, abre el FileChooser
 * Guardo el contenido del archivo original en la constante Buffer para, a la hora de crear un archivo nuevo vacío o abrir otro archivo existente, comprobar si se han hecho cambios.
 * De este modo sé si es necesario mostrar el diálogo de guardar para que el usuario no pierda sus cambios
 * @param evt 
 */
    private void BotonAbrirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAbrirArchivoActionPerformed

    if(AreaTexto.getText().length()>0&EtiquetaNombreArchivo.getText().length()==0){
        dialogoGuardar.setVisible(true);
    }else if(AreaTexto.getText().length()>0&EtiquetaNombreArchivo.getText().length()>0&buffer!=AreaTexto.getText()){
        dialogoGuardar.setVisible(true);
    }else{      
        int status = FileChooser.showOpenDialog(null);
        String textoEntero="";
        String linea="";
           if(status==0){
               archivoEditado=FileChooser.getSelectedFile();
               FunUbicacion.setText(archivoEditado.getPath());
               EtiquetaNombreArchivo.setText(archivoEditado.getName());

            try {
                BufferedReader lector = new BufferedReader(new FileReader(FileChooser.getSelectedFile()));
                while((linea=lector.readLine())!=null){ 
                textoEntero+=linea;
                }
                if(lector.readLine()==null){
                 buffer=textoEntero;
                }
                AreaTexto.setText(textoEntero);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(editor.class.getName()).log(Level.SEVERE, null, ex);
                AreaTexto.setText("No se ha podido abrir el archivo");
            } catch (IOException ex) {
                Logger.getLogger(editor.class.getName()).log(Level.SEVERE, null, ex);
            }

       }
    }
       
    }//GEN-LAST:event_BotonAbrirArchivoActionPerformed

    private void FileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileChooserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FileChooserActionPerformed

    private void MenuArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuArchivoActionPerformed
        
    }//GEN-LAST:event_MenuArchivoActionPerformed

    private void BotonAbrirArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAbrirArchivoMouseClicked
    }//GEN-LAST:event_BotonAbrirArchivoMouseClicked

    private void AreaTextoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AreaTextoKeyPressed
          
    }//GEN-LAST:event_AreaTextoKeyPressed
/**
 * Este método sobreescribe un archivo ya existente con los cambios hechos por el usuario
 * Si el archivo no está previamente creado se guarda como un archivo nuevo, igual que en el método BotonGuardarComoActionPerformed()
 * @param evt 
 */
    private void BotonGuardarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarArchivoActionPerformed
 // Si hay algo escrito pero no está guardado en un archivo:
    if(AreaTexto.getText().length()>0&EtiquetaNombreArchivo.getText().length()==0){
        File saver;
        PrintWriter printwriter = null;
        int status = FileSaver.showSaveDialog(jPanel1);
        
        if (status==0) {
            try {
                saver = FileSaver.getSelectedFile();
                printwriter = new PrintWriter(saver);
                printwriter.write(AreaTexto.getText());
                printwriter.close();
                EtiquetaNombreArchivo.setText(FileSaver.getSelectedFile().getName());
                FunUbicacion.setText(FileSaver.getSelectedFile().getPath());
            } catch (FileNotFoundException ex) {
            Logger.getLogger(editor.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }
        
    }else{
            PrintWriter printwriter = null;
            try {
                printwriter = new PrintWriter(archivoEditado);
                printwriter.write(AreaTexto.getText());
                printwriter.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(editor.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                printwriter.close();
            }
        }
    }//GEN-LAST:event_BotonGuardarArchivoActionPerformed
/**
 * Este método borra lo que hay en el AreaTexto para que el usuario pueda escribir su nuevo documento de texto
 * En caso de que haya texto escrito a la hora de hacer clic en el botón 'nuevo':
 * 
 * Si hay texto escrito que no viene de un arhivo previamente guardado, muestro el dialogo de guardado
 * Si hay texto escrito que sí viene de un archivo previamente guardado pero que ha sido modificado, muestro el dialogo de guardado
 * Si hay texto escrito que sí viene de un archivo previamente guardado pero que NO ha sido modificado, vacío el area de texto y la etiqueta de nombre de archivo
 * @param evt 
 */
    private void BotonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNuevoActionPerformed
//
//        System.out.println(buffer);
//        System.out.println(AreaTexto.getText());
//        if(buffer==AreaTexto.getText()){
//            System.out.println("Iguales");
//        }else{
//            System.out.println("diferentes");
//        }
        if(AreaTexto.getText().length()>0 & EtiquetaNombreArchivo.getText()==""){
            dialogoGuardar.setVisible(true);
            }else if(AreaTexto.getText().length()>0 & EtiquetaNombreArchivo.getText()!="" & AreaTexto.getText()!=buffer){
                dialogoGuardar.setVisible(true);
                }else if(AreaTexto.getText().length()>0 & EtiquetaNombreArchivo.getText()!="" & AreaTexto.getText()==buffer){
                    FunUbicacion.setText("");
                    AreaTexto.setText("");
                    EtiquetaNombreArchivo.setText("");
                    buffer="";
                    
                }    
        
    }//GEN-LAST:event_BotonNuevoActionPerformed
/**
 * Este método en esencia hace lo mismo que el botón guardar
 * Si no está guardado se hace un guardar como, y en caso contrario se sobreescribe el documento ya existente
 * @param evt 
 */
    private void BotonGuardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardar2ActionPerformed
        
        if(archivoEditado.getName().toString()!=null){
            PrintWriter printwriter = null;
        try {
            printwriter = new PrintWriter(archivoEditado);
            printwriter.write(AreaTexto.getText());                  
            printwriter.close();
            dialogoGuardar.dispose();
            AreaTexto.setText("");
            EtiquetaNombreArchivo.setText("");
            FunUbicacion.setText("");
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(editor.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            printwriter.close();
        }
        }else{
                File saver;
                PrintWriter printwriter = null;
                int status = FileSaver.showSaveDialog(jPanel1);
                if (status==0) {
                    try {
                        saver = FileSaver.getSelectedFile();
                        printwriter = new PrintWriter(saver);
                        printwriter.write(AreaTexto.getText());
                        printwriter.close();

                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(editor.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
                
            }
        
    }//GEN-LAST:event_BotonGuardar2ActionPerformed
/**
 * Este método se ejecuta cuando el usuario decide no guardar el texto que se encuentra en el AreaTexto
 * Vacía el AreaTextom la EtiquetaNombreArchivo, la FunUbicación y el buffer
 * Posteriormente cierra la ventana dialogoGuardar
 * @param evt 
 */
    private void BotonNoGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNoGuardarActionPerformed
        AreaTexto.setText("");
        dialogoGuardar.dispose();
        EtiquetaNombreArchivo.setText("");
        FunUbicacion.setText("");
        buffer="";
        
    }//GEN-LAST:event_BotonNoGuardarActionPerformed
/**
 * Este método simplemente cierra la ventana dialogoGuardar sin alterar ningún otro elemento
 * @param evt 
 */
    private void BotonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancelarActionPerformed
        dialogoGuardar.dispose();
    }//GEN-LAST:event_BotonCancelarActionPerformed

    private void FileSaverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileSaverActionPerformed
           
    }//GEN-LAST:event_FileSaverActionPerformed

    private void MenuFormatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFormatoActionPerformed
        
    }//GEN-LAST:event_MenuFormatoActionPerformed
/**
 * Este método muestra el diálogo dialogFormato, donde el usuario puede modificar el formato de su texto
 * @param evt 
 */
    private void BotonCambiarFormatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCambiarFormatoActionPerformed
        DialogFormato.setVisible(true);
    }//GEN-LAST:event_BotonCambiarFormatoActionPerformed

    private void ComboBoxFuenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxFuenteActionPerformed
        
    }//GEN-LAST:event_ComboBoxFuenteActionPerformed
/**
 * Modifica el tamaño de la fuente de acuerdo con las necesidades del usuario
 * @param evt 
 */
    private void SpinnerTamañoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpinnerTamañoStateChanged
        AreaTexto.setFont(new Font(AreaTexto.getFont().getFamily(),Font.PLAIN, (int) SpinnerTamaño.getValue()));
    }//GEN-LAST:event_SpinnerTamañoStateChanged
/**
 * Modifica el color del texto que hay en AreaTexto
 * @param evt 
 */
    private void BotonColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonColorActionPerformed
        Color color = ColorChooser.showDialog(null,"Elige un color",Color.black);
        AreaTexto.setForeground(color);
    }//GEN-LAST:event_BotonColorActionPerformed

    private void BotonCancelarColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancelarColorActionPerformed
    }//GEN-LAST:event_BotonCancelarColorActionPerformed
/**
 * Modifica la fuente del texto que hay en AreaTexto
 * @param evt 
 */
    private void ComboBoxFuenteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxFuenteItemStateChanged
        AreaTexto.setFont(new Font((String)ComboBoxFuente.getSelectedItem(),Font.PLAIN,AreaTexto.getFont().getSize()));
    }//GEN-LAST:event_ComboBoxFuenteItemStateChanged
/**
 * Este método contiene un Switch dependiendo en la opción que el usuario seleccione en el menú de más estilos
 * Para capitalizar,se divide el texto en un array de Strings y sustituyo el primer carácter de cada String por el mismo carácter en mayúscula. Se mete cada elemento del array en otro String que se introducirá en el AreaTexto
 * Para el Camel Case, se hace lo mismo que para capitalizar, pero eliminando los espacios
 * @param evt 
 */
    private void ComboBoxMasEstilosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxMasEstilosActionPerformed
        switch(ComboBoxMasEstilos.getSelectedIndex()){
            
        case 0:
//            CAPITALIZAR
            String[] Split = AreaTexto.getText().split(" ");
            String nuevotexto="";
            for(String palabra:Split){
                palabra=palabra.toLowerCase();
                palabra=palabra.replace(palabra.charAt(0), Character.toUpperCase(palabra.charAt(0)));
                nuevotexto+=palabra+" ";
                
            }
            System.out.println(nuevotexto);
            AreaTexto.setText(nuevotexto);

            break;
        case 1:
//          PASAR A MAYUSCULAS
            AreaTexto.setText(AreaTexto.getText().toUpperCase());
            break;
        case 2:
//            PASAR A MINUSCULAS
            AreaTexto.setText(AreaTexto.getText().toLowerCase());
            break;
//            CAMEL CASE
        case 3:
           String[] Split1 = AreaTexto.getText().split(" ");
            String nuevotexto1="";
            for(String palabra:Split1){
                palabra=palabra.toLowerCase();
                palabra=palabra.replace(palabra.charAt(0), Character.toUpperCase(palabra.charAt(0)));
                nuevotexto1+=palabra;  
            }
            AreaTexto.setText(nuevotexto1);
            break;
//            QUITAR CARACTERES ESPECIALES
        case 4:
            AreaTexto.setText(AreaTexto.getText().replaceAll("[^a-zA-Z0-9á-úÁ-ÚñÑ ]", ""));
        }
    }//GEN-LAST:event_ComboBoxMasEstilosActionPerformed

 /**
  * Se Calculan los datos del archivo cuando el usuario pasa con el ratón encima de EtiquetaDatos o de PanelDatos
  * Las palabras se  dividiendo el texto dentro de AreaTexto en un array de strings
  * El color de fondo del panel cambia a azul
  * @param evt 
  */
    private void EtiquetaDatosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EtiquetaDatosMouseEntered
         ArrayList<String> cuenta = new ArrayList<>();
        
        String[] Split = AreaTexto.getText().split(" ");
        Integer longpalabras = Split.length;
        String longitud = longpalabras.toString();
        
        Integer longcaracteres=AreaTexto.getText().length();
        String longitudcaracteres= longcaracteres.toString();
        
        if(EtiquetaNombreArchivo.getText()!=""){
             try {
                 Path ruta = Paths.get(archivoEditado.getPath());
                 long tamaño = Files.size(ruta);
                 String tamarchivo=Long.toString(tamaño);
                 FunTamaño.setText(tamarchivo);
             } catch (IOException ex) {
                 Logger.getLogger(editor.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
        FunPalabras.setText(longitud);
        FunCaracteres.setText(longitudcaracteres);
        PanelDatos.setBackground(new Color(61,182,234));
        DialogoDatos.setVisible(true);
           
    }//GEN-LAST:event_EtiquetaDatosMouseEntered
/**
 * Cuando el usuario quita el ratón de encima de EtiquetaDatos o de PanelDatos, se cierra el DialogoDatos
 * y el color de fono del panel vuelve a ser el original
 * @param evt 
 */
    private void EtiquetaDatosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EtiquetaDatosMouseExited
        PanelDatos.setBackground(new Color(214,217,224));
        DialogoDatos.dispose();

    }//GEN-LAST:event_EtiquetaDatosMouseExited

    private void PanelDatosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelDatosMouseEntered
        ArrayList<String> cuenta = new ArrayList<>();
        
        String[] Split = AreaTexto.getText().split(" ");
        Integer longpalabras = Split.length;
        String longitud = longpalabras.toString();
        
        Integer longcaracteres=AreaTexto.getText().length();
        String longitudcaracteres= longcaracteres.toString();
        
        if(EtiquetaNombreArchivo.getText().length()>0){
            long tamaño = archivoEditado.getTotalSpace();
            String tamarchivo=Long.toString(tamaño);
            FunTamaño.setText(tamarchivo);
        }
        FunPalabras.setText(longitud);
        FunCaracteres.setText(longitudcaracteres);
        PanelDatos.setBackground(new Color(61,182,234));

        
        DialogoDatos.setVisible(true);
    }//GEN-LAST:event_PanelDatosMouseEntered

    private void PanelDatosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelDatosMouseExited
        PanelDatos.setBackground(new Color(214,217,224));
        DialogoDatos.dispose();
    }//GEN-LAST:event_PanelDatosMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaTexto;
    public javax.swing.JMenuItem BotonAbrirArchivo;
    private javax.swing.JMenuItem BotonCambiarFormato;
    private javax.swing.JToggleButton BotonCancelar;
    private javax.swing.JButton BotonCancelarColor;
    private javax.swing.JButton BotonColor;
    private javax.swing.JMenuItem BotonDatosDel;
    private javax.swing.JToggleButton BotonGuardar2;
    private javax.swing.JMenuItem BotonGuardarArchivo;
    private javax.swing.JMenuItem BotonGuardarComo;
    private javax.swing.JToggleButton BotonNoGuardar;
    private javax.swing.JMenuItem BotonNuevo;
    private javax.swing.JButton BotonSeleccionarColor;
    private javax.swing.JColorChooser ColorChooser;
    private javax.swing.JComboBox<String> ComboBoxFuente;
    private javax.swing.JComboBox<String> ComboBoxMasEstilos;
    private javax.swing.JDialog DialogFormato;
    private javax.swing.JFrame DialogoDatos;
    private javax.swing.JLabel EtiquetaDatos;
    private javax.swing.JLabel EtiquetaNombreArchivo;
    private javax.swing.JFileChooser FileChooser;
    private javax.swing.JFrame FileChooserFrame;
    private javax.swing.JFileChooser FileSaver;
    private javax.swing.JFrame FileSaverFrame;
    private javax.swing.JFrame FrameColorChooser;
    private javax.swing.JLabel FunCaracteres;
    private javax.swing.JLabel FunPalabras;
    private javax.swing.JLabel FunTamaño;
    private javax.swing.JLabel FunUbicacion;
    private javax.swing.JMenu MenuAcercaDe;
    private javax.swing.JMenu MenuArchivo;
    private javax.swing.JMenu MenuFormato;
    private javax.swing.JDialog ModalAcercaDe;
    private javax.swing.JPanel PanelDatos;
    private javax.swing.JSpinner SpinnerTamaño;
    private javax.swing.JDialog dialogoGuardar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
